version: '3'
services: 
  api:
    build: ./api
    container_name: api
    ports:
      - "80:80"
    volumes:
      - ./api:/usr/src/app
  my-webpage:
    build: .
    container_name: my-webpage
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
  mysql-svc:
    image: mysql
    container_name: mysql
    command: --init-file /data/application/init-MySQL.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password    
    volumes:
      # Bind mount
      - ./init-MySQL.sql:/data/application/init-MySQL.sql
      - mysql-volume:/var/lib/mysql
  
  # The adminer image is a web-based database management tool that allows you to manage MySQL, PostgreSQL, and other database systems through a web interface.
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

# Named volumes
volumes:
  mysql-volume:
